server:
  port: 10005
spring:
  cloud:
    gateway:
      routes:
          - id: prefixpath_licensing_route
            uri: lb://LICENSINGSERVICE #此处需要使用lb协议
            predicates:
              - Path=/license/**
            filters:
              - StripPrefix=1
              - PrefixPath=/v1
          - id: prefixpath_organization_route
            uri: lb://ORGANIZATIONSERVICE #此处需要使用lb协议
            predicates:
              - Path=/org/**
            filters:
              - StripPrefix=1
              - PrefixPath=/v1
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${com.sap.andyhecd.microservice.eureka.server.host}:${com.sap.andyhecd.microservice.eureka.server.port}/eureka/
    healthcheck:
      enabled: true


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway