version: '3'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: microservice
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  chapter1:
    restart: on-failure
    build: ./chapter1
    image: andyhecd/chapter1:0.0.1-SNAPSHOT
    container_name: chapter1
    expose:
      - "10701"
    ports:
      - 10701:10701

  chapter2:
    restart: on-failure
    build: ./chapter2
    image: andyhecd/chapter2-licensing-service:0.0.1-SNAPSHOT
    container_name: chapter2-licensing-service
    expose:
      - "10702"
    ports:
      - 10702:10702

  chapter3-configserver:
    restart: on-failure
    build: ./chapter3
    image: andyhecd/chapter3-confsvr.jar:0.0.1-SNAPSHOT
    container_name: chapter3-confsvr.jar
    expose:
      - "10703"
    ports:
      - 10703:10703
    environment:
       ENCRYPT_KEY: "IMSYMMETRIC"

  chapter3-licensingservice:
    restart: on-failure
    build: ./chapter3
    image: andyhecd/chapter3-licensing-service:0.0.1-SNAPSHOT
    ports:
      - "11703:11703"
    environment:
      WAIT_HOSTS: mysql:3306
      PROFILE: "prod"
      CONFIGSERVER_URI: "http://chapter3-configserver:10703"
      CONFIGSERVER_PORT:   "10703"
      DATABASESERVER_PORT: "3306"
      ENCRYPT_KEY: "IMSYMMETRIC"
    depends_on:
      - docker-mysql