version: '3'
services:
  microservice-mysql:
    restart: always
    container_name: microservice-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: microservice
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 10000:3306

  config-server:
    restart: on-failure
    build: ./config-server
    image: andyhecd/config-server:0.0.1-SNAPSHOT
    container_name: config-server
    expose:
      - 10001
    ports:
      - 10001:10001
    environment:
      - ENCRYPT_KEY=IMSYMMETRIC

  eureka-server:
    restart: on-failure
    build: ./eureka-server
    image: andyhecd/eureka-server:0.0.1-SNAPSHOT
    container_name: eureka-server
    expose:
      - 10002
    ports:
      - 10002:10002
    depends_on:
      - config-server
    environment:
      - PROFILE=prod
      - ENCRYPT_KEY=IMSYMMETRIC
      - WAIT_HOSTS=config-server:10001
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    command: sh -c "/wait && /run.sh"

  gateway-server:
    restart: on-failure
    build: ./gateway-server
    image: andyhecd/gateway-server:0.0.1-SNAPSHOT
    container_name: gateway-server
    expose:
      - 10005
    ports:
      - 10005:10005
    depends_on:
      - config-server
      - eureka-server
    environment:
      - PROFILE=prod
      - ENCRYPT_KEY=IMSYMMETRIC
      - WAIT_HOSTS=config-server:10001, eureka-server:10002
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    command: sh -c "/wait && /run.sh"

  organization-service:
    restart: on-failure
    build: ./organization-service
    image: andyhecd/organization-service:0.0.1-SNAPSHOT
    container_name: organization-service
    expose:
      - 10004
    ports:
      - 10004:10004
    depends_on:
      - config-server
      - microservice-mysql
      - eureka-server
    environment:
      - PROFILE=prod
      - WAIT_HOSTS=microservice-mysql:3306, config-server:10001, eureka-server:10002
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - ENCRYPT_KEY=IMSYMMETRIC
    command: sh -c "/wait && /run.sh"

  licensing-service:
    restart: on-failure
    build: ./licensing-service
    image: andyhecd/licensing-service:0.0.1-SNAPSHOT
    container_name: licensing-service
    expose:
      - 10003
    ports:
      - 10003:10003
    depends_on:
      - config-server
      - microservice-mysql
      - eureka-server
      - organization-service
    environment:
      - PROFILE=prod
      - WAIT_HOSTS=microservice-mysql:3306, config-server:10001, eureka-server:10002, organization-service:10004
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - ENCRYPT_KEY=IMSYMMETRIC
    command: sh -c "/wait && /run.sh"