example.organization.property: "I AM THE DEFAULT ORGANIZATION SERVICE"
com.sap.andyhecd.microservice.eureka.server.host: localhost
com.sap.andyhecd.microservice.eureka.server.port: 10002
spring.datasource.url: jdbc:mysql://localhost:3306/microservice
spring.datasource.username: root
spring.datasource.password: "{cipher}a4a5316fdcf2b5ae36f2a72bbddcf7518985f1666766e1b15b8be203d058cab3"
lombok.equalsAndHashCode.callSuper: call
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.testWhileIdle: true
spring.datasource.initialization-mode: always
spring.datasource.validationQuery: SELECT 1
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"
