server:
  port: 10002

eureka:
  instance:
    hostname: ${com.sap.andyhecd.microservice.eureka.server.host}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
    #默认30s; 
    #eureka server刷新readCacheMap的时间，注意，client读取的是readCacheMap，这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上
    #responseCacheUpdateIntervalMs: 3000 
    #eureka server缓存readWriteCacheMap失效时间，这个只有在这个时间过去后缓存才会失效，失效前不会更新，过期后从registry重新读取注册服务信息，
    #registry是一个ConcurrentHashMap, 由于启用了evict其实就用不太上改这个配置了
    #默认180s
    #responseCacheAutoExpirationInSeconds: 180 
    #启用主动失效，并且每次主动失效检测间隔为3s
    #eviction-interval-timer-in-ms: 3000